Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic
operations like:
a) Addition of 2 in all the element
b) Multiply 3 with all the elements
c) Divide every element by 2

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print("Original Array:", arr)

arr_add = arr + 2
print("After Addition (+2):", arr_add)

arr_multiply = arr * 3
print("After Multiplication (*3):", arr_multiply)

arr_divide = arr / 2
print("After Division (/2):", arr_divide)


Original Array: [10 20 30 40 50]
After Addition (+2): [12 22 32 42 52]
After Multiplication (*3): [ 30  60  90 120 150]
After Division (/2): [ 5. 10. 15. 20. 25.]


Q.2 Questions on Basic NumPy Array:
a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 6, 4, 5])
print("Original Array:", arr)

arr_reversed = arr[::-1]
print("Reversed Array:", arr_reversed)


Original Array: [1 2 3 6 4 5]
Reversed Array: [5 4 6 3 2 1]


b) Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [ ]:
import numpy as np

def most_frequent(arr):
    """Find the most frequent value and its indices in a NumPy array"""
    values, counts = np.unique(arr, return_counts=True)
    max_count_index = np.argmax(counts)
    most_frequent_value = values[max_count_index]
    indices = np.where(arr == most_frequent_value)[0]

    return most_frequent_value, indices

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

value_x, indices_x = most_frequent(x)
value_y, indices_y = most_frequent(y)

print("For array x:", x)
print(f"Most frequent value: {value_x}, Indices: {indices_x}")

print("\nFor array y:", y)
print(f"Most frequent value: {value_y}, Indices: {indices_y}")


For array x: [1 2 3 4 5 1 2 1 1 1]
Most frequent value: 1, Indices: [0 5 7 8 9]

For array y: [1 1 1 2 3 4 2 4 3 3]
Most frequent value: 1, Indices: [0 1 2]


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:
a) Access 1st row, 2nd column
b) Access 3rd row, 1st column

In [ ]:
import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

element1 = arr[0, 1]

element2 = arr[2, 0]

print("Element at 1st row, 2nd column:", element1)
print("Element at 3rd row, 1st column:", element2)


Element at 1st row, 2nd column: 20
Element at 3rd row, 1st column: 70


Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?

In [ ]:
import numpy as np

Cyrush = np.linspace(10, 100, 25)

print(f"Dimensions of the array: {Cyrush.ndim}")

print(f"Shape of the array: {Cyrush.shape}")

print(f"Total number of elements in the array: {Cyrush.size}")

print(f"Data type of each element in the array: {Cyrush.dtype}")

print(f"Total number of bytes consumed by the array: {Cyrush.nbytes}")

reshaped_array = Cyrush.reshape(-1, 1)
print(f"Reshaped array (Transpose using reshape()):\n{reshaped_array}")

transpose_array = Cyrush[:, np.newaxis]
print(f"Transpose using T attribute:\n{transpose_array}")


Dimensions of the array: 1
Shape of the array: (25,)
Total number of elements in the array: 25
Data type of each element in the array: float64
Total number of bytes consumed by the array: 200
Reshaped array (Transpose using reshape()):
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transpose using T attribute:
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]


Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>>
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean,
median, max, min, unique elements. Reshape the array to four rows and three columns and
name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three
columns and name it as resized_ ucs420_<your_name>>.

In [ ]:
import numpy as np

ucs420_Cyrush = np.array([[10, 20, 30, 40],
                          [50, 60, 70, 80],
                          [90, 15, 20, 35]])

mean_val = np.mean(ucs420_Cyrush)
median_val = np.median(ucs420_Cyrush)
max_val = np.max(ucs420_Cyrush)
min_val = np.min(ucs420_Cyrush)
unique_elements = np.unique(ucs420_Cyrush)

print(f"Mean: {mean_val}")
print(f"Median: {median_val}")
print(f"Max: {max_val}")
print(f"Min: {min_val}")
print(f"Unique elements: {unique_elements}")

reshaped_ucs420_Cyrush = ucs420_Cyrush.reshape(4, 3)
print(f"Reshaped array (4x3):\n{reshaped_ucs420_Cyrush}")

resized_ucs420_Cyrush = ucs420_Cyrush.flatten()[:6].reshape(2, 3)
print(f"Resized array (2x3):\n{resized_ucs420_Cyrush}")


Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped array (4x3):
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized array (2x3):
[[10 20 30]
 [40 50 60]]
